FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm install

COPY . .

RUN npm run prisma:generate

EXPOSE 3000

CMD ["sh", "-c", "npm run prisma:migrate && npm run dev -- --turbo"]
