FROM oven/bun:1.3-debian

WORKDIR /app

COPY package.json bun.lock* ./

RUN bun install

COPY . .

RUN bun run prisma:generate

EXPOSE 3000

CMD ["sh", "-c", "bun run prisma:migrate && bun run dev --turbo"]
